name:                yesod-form-bootstrap4
version:             0.1.1
synopsis:            renderBootstrap4
github:              ncaq/yesod-form-bootstrap4
license:             MIT
author:              ncaq
maintainer:          ncaq@ncaq.net
copyright:           © ncaq
category:            Web

dependencies:
  - base >= 4.7 && < 5
  - classy-prelude-yesod
  - yesod-form

library:
  source-dirs: src
