name:                yesod-form-bootstrap4
version:             1.0.1
synopsis:            renderBootstrap4
github:              ncaq/yesod-form-bootstrap4
license:             MIT
author:              ncaq
maintainer:          ncaq@ncaq.net
copyright:           © ncaq
category:            Web

dependencies:
  - base >= 4.7 && < 5
  - shakespeare
  - text
  - yesod-core
  - yesod-form

library:
  source-dirs: src
